Vagrant.configure("2") do |config|
  config.vm.define "ychunS" do |server|
    server.vm.box = "generic/ubuntu1804"
    server.vm.hostname = "ychunS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "ychunS"
    end
    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      sudo chmod 644 /etc/rancher/k3s/k3s.yaml
      echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /home/vagrant/.bashrc
      cat << EOF > "/home/vagrant/ingress.yaml"
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: app1
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
EOF
      sleep 5
      kubectl apply -f /home/vagrant/ingress.yaml
    SHELL
  end
end