Vagrant.configure("2") do |config|
  config.vm.define "ychunS" do |server|
    server.vm.box = "generic/ubuntu2204"
    server.vm.hostname = "ychunS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "ychunS"
    end
    server.vm.provision "shell", inline: <<-SHELL
      apt-get update -y && apt-get install -y curl net-tools
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" sh -
      
      NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
      while [ ! -e ${NODE_TOKEN} ]; do
        sleep 2
      done

      mkdir -p /tmp/token-share
      sudo cat ${NODE_TOKEN} > /tmp/token-share/node-token
      cd /tmp/token-share && nohup python3 -m http.server 8080 &>/dev/null &
    SHELL
  end

  config.vm.define "schaehunSW" do |worker|
    worker.vm.box = "generic/ubuntu2204"
    worker.vm.hostname = "schaehunSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "schaehunSW"
    end
    worker.vm.provision "shell", inline: <<-SHELL
      apt-get update -y && apt-get install -y curl net-tools
      NODE_TOKEN=""
      while [ -z "$NODE_TOKEN" ]; do
        NODE_TOKEN=$(curl -sf http://192.168.56.110:8080/node-token 2>/dev/null)
        echo "Waiting for node-token from server..."
        sleep 2
      done
      
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${NODE_TOKEN} sh -
    SHELL
  end
end
